
POST http://localhost:8000/api/users HTTP/1.1
content-type: application/json

{
    "firstName": "sample",
    "lastName": "sample",
    "userName": "guydudebro",
    "email": "guy@brodude.com",
    "password": "3452"
}
